# .markdownlint.yaml

# Разрешить определённые HTML-теги (MD033)
MD033:
  allowed_elements: ["kbd", "br"]

# Ограничение длины строки: 80 символов, но не для таблиц и блоков кода
MD013:
  line_length: 80
  tables: false       # ← игнорировать таблицы
  code_blocks: false  # ← игнорировать блоки кода (опционально, но полезно)