# .markdownlint.yaml

# Разрешить определённые HTML-теги (MD033)
MD033:
  allowed_elements: ["kbd", "br"]

# Ограничение длины строки: 80 символов, но не для таблиц и блоков кода
MD013:
  line_length: 110
  code_blocks: false
  tables: false