name: "Nextcloud User Files Backup"
description: "Backup Nextcloud user files to external USB drive"
version: "0.1.0"
slug: "nc_user_files_backup"
url: "https://github.com/alekslegkih/nc_user_files_backup"
arch:
  - aarch64
  - amd64
  - armv7
image: "ghcr.io/alekslegkih/nc_user_files_backup-{arch}"
startup: once
boot: manual
init: false
hassio_api: true
hassio_role: backup
homeassistant_api: true
options:
  ha_token: ""
schema:
  ha_token: password
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - addons:r
usb: true
