name: Nextcloud User Files Backup Dev

on:
  push:
    branches: [develop]

jobs:
  build-and-publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug file structure
      run: |
        echo "Files in repo:"
        ls -la
        echo "Files in dev folder:"
        ls -la nc_user_files_backup_dev/  # ← ИСПРАВЛЕНО!

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push dev image
      uses: docker/build-push-action@v5
      with:
        context: ./nc_user_files_backup_dev  # ← ИСПРАВЛЕНО!
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-${{ matrix.arch }}:0.0.1
          ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-${{ matrix.arch }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify pushed images
      run: |
        echo "✅ Build completed! Checking pushed images..."
        for arch in aarch64 amd64 armv7; do
          echo "Checking nc_user_files_backup_dev-${arch}:"
          curl -s "https://ghcr.io/v2/alekslegkih/nc_user_files_backup_dev-${arch}/tags/list" | jq . || echo "Image not found or access denied"
        done

    - name: Completion message
      run: |
        echo "🎉 Dev version 0.0.1 built successfully!"
        echo "📦 Images pushed to:"
        echo "   ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-aarch64:0.0.1"
        echo "   ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-amd64:0.0.1" 
        echo "   ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-armv7:0.0.1"