name: Nextcloud User Files Backup Dev

on:
  push:
    branches: [develop]

jobs:
  build-and-publish-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    strategy:
      matrix:
        arch: [aarch64, amd64, armhf]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug file structure
      run: |
        echo "Files in repo:"
        ls -la
        echo "Files in dev folder:"
        ls -la nc_user_files_backup_dev/

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push dev image
      uses: docker/build-push-action@v5
      with:
        context: ./nc_user_files_backup_dev
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-${{ matrix.arch }}:0.0.1
          ghcr.io/${{ github.repository_owner }}/nc_user_files_backup_dev-${{ matrix.arch }}:latest

    - name: Completion message
      run: echo "Dev version 0.0.1 built for ${{ matrix.arch }}!"